controller_list:
  - name: fake_Rail_controller
    type: $(arg execution_type)
    joints:
      []
  - name: fake_Arm_controller
    type: $(arg execution_type)
    joints:
      - arm_joint_a1
      - arm_joint_a2
      - arm_joint_a3
      - arm_joint_a4
      - arm_joint_a5
      - arm_joint_a6
  - name: fake_Hand_controller
    type: $(arg execution_type)
    joints:
      - arm_joint_a6
initial:  # Define initial robot poses.
  - group: Arm
    pose: Home